### ISSUE TITLE
The extraTunnelHeaders is not sent while making a request in 1.4.x

### ISSUE THREAD

**Issue by TaeHyunChi** [tophcodes/guacamole-common-js#17]
The extraTunnelHeaders is not sent while making a request in 1.4.x 
so I did fix it by restoring version 1.3.1

_Originally posted by @TaeHyunChi in https://github.com/padarom/guacamole-common-js/issues/16#issuecomment-1073695791_

**Comment by padarom** [comment]
Were you using `1.4.0`? After this was reported in #16 I published a follow-up patch `1.4.0-a`. I just installed that version locally and to me its files look fine:

![Uploading Bildschirmfoto 2022-03-28 um 13.55.43.png…]()

**Comment by AndreasHerz** [comment]
Why not `@1.4.1`? I guess it`s not a pre-release 🤔

**Comment by padarom** [comment]
Because I want to keep the versioning scheme of this npm library in line with upstream Guacamole. If they end up releasing 1.4.1 it clashes with the version number I chose, see https://github.com/padarom/guacamole-common-js#version-numbers
