### ISSUE TITLE
can not get socket obj in WebSocketTunnel  

### ISSUE THREAD

**Issue by try-to-be-brave** [tophcodes/guacamole-common-js#21]
hello,I want to customize some of my own actions based on the messages the websocket receives. but the socket obj is private in WebSocketTunnel. can you make it public?

**Comment by padarom** [comment]
Hi there, I do not maintain or modify the original source, with this fork I merely publish the existing sources to npm. If you want this changed you'd have to go to http://guac-dev.org/trac/
