### ISSUE TITLE
How to update types in @types/guacamole-common-js

### ISSUE THREAD

**Issue by Georgegriff** [tophcodes/guacamole-common-js#24]
Hi i notice that the types https://www.npmjs.com/package/@types/guacamole-common-js  are not present for the latest version 1.4.1a on Definitely Typed.

What is the process to get these generated? I'm happy to contribute it but I don't know where to start.

**Comment by padarom** [comment]
Hi there, the types are all defined in a third-party package in the `DefinitelyTyped/DefinitelyTyped` repo. You can look at their [contribution guide](https://github.com/DefinitelyTyped/DefinitelyTyped#edit-an-existing-package) to see how to make changes to the types and contribute to their repo.

Specifically, the type definitions are here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/guacamole-common-js
