### ISSUE TITLE
Upgrade Version for 1.5.0

### ISSUE THREAD

**Issue by rysinal** [tophcodes/guacamole-common-js#26]
Hi, guacamole version is 1.5.0, should we upgrade it ?
https://guacamole.apache.org/releases/1.5.0/

**Comment by tophcodes** [comment]
Thanks for letting me know. It seems like the fork origin of this repo (`glyptodon/guacamole-client`) has switched its purpose to only contain Guacamole enterprise now, so the original sources have moved to `apache/guacamole-client`. This makes it a bit harder to track changes committed to upstream as GitHub is now tracking the wrong repository.

I just updated the sources from the new upstream though and published version 1.5.0.
